max limit
dockstore/compose_setup pull request #204
Opened 2021-08-18 00:26 UTC by NatalieEO

https://ucsc-cgl.atlassian.net/browse/SEAB-3181

2021-08-18 14:14 UTC, denis-yuen approved these changes
:man_shrugging: 

Probably should really  https://ucsc-cgl.atlassian.net/browse/SEAB-3060 it, but I'll allow it

2021-08-19 16:16 UTC, coverbeck requested changes
1. You need to add a line in the block starting around line 427
2. You need to update templates/web.yml.template

2021-08-19 17:05 UTC, coverbeck requested changes

2021-08-19 17:05 UTC, coverbeck commented on install_bootstrap
> +"ELASTICSEARCH_MAX_CONCURRENT_SESSIONS":"${elasticsearch_max_concurrent_sessions}""
Last double quote at the end of line needs to be a comma instead.

2021-08-20 17:12 UTC, garyluu approved these changes

2021-08-23 18:32 UTC, coverbeck approved these changes

2021-08-23 18:42 UTC, merged